### ISSUE TITLE
Build the file in the npm package instead of in postinstall

### ISSUE THREAD

**Issue by adamburgess** [treywood/babel-plugin-bluebird-async-functions#2]
doing it that way makes it work on JSPM, which doesn't run postinstall scripts
also allows you to make all dependencies devDependencies (i.e. unneeded)

**Comment by treywood** [comment]
I've replaced the 'postinstall' with 'prepublish', so the plugin should be built before you install it. The dependencies listed under 'dependencies' are all runtime dependencies, and are required to run the plugin.

**Comment by chpio** [comment]
> The dependencies listed under 'dependencies' are all runtime dependencies, and are required to run the plugin.

no, they are _not_. They are required by babel but not by the plugin.

edit: bluebird is required by the app but again not by the plugin.
