### ISSUE TITLE
Suggested Way to Load BlueBird Globally

### ISSUE THREAD

**Issue by dtothefp** [treywood/babel-plugin-bluebird-async-functions#3]
I've looked around and not found a good way to replace the native es6 promise with bluebird. I tried below in my entry file

``` js
global.Promise = require('bluebird');

Promise.config({
  warnings: false,
  longStackTraces: true,
  cancellation: true
});

require('./entry');
```

but still get this error in a subsequently `import`ed file

``` js
exports.default = Promise.coroutine(regeneratorRuntime.mark(function _callee(_ref) {
```

**Comment by dtothefp** [comment]
NVM I was being stupid, had to `require` the `babel-polyfill` first, not after..duhh

``` js
requre('babel-polyfill');
global.Promise = require('bluebird');

Promise.config({
  warnings: false,
  longStackTraces: true,
  cancellation: true
});
```

for some reason `import` doesn't work though?

won't work

``` js
import 'babel-polyfill';
import Promise from  'bluebird';

global.Promise = Promise;
```

**Comment by treywood** [comment]
Are you using the es2015 Babel preset? It should include support for import statements.
