### ISSUE TITLE
import bluebird

### ISSUE THREAD

**Issue by chpio** [treywood/babel-plugin-bluebird-async-functions#5]
This plugin requires a global Promise (or a polyfill) to exist which is messy (IMO).

We could also import bluebird into the module with a simple change:

``` javascript
let asyncWrap = t.memberExpression(bluebird, t.identifier(methodName));
// to
let asyncWrap = t.memberExpression(state.addImport('bluebird', 'default', node.name), t.identifier(methodName));
```

https://github.com/treywood/babel-plugin-bluebird-async-functions/blob/4f27daa475f45ca69b9d759ecd560405a83a2faf/src/functionTransform.js#L23

adopted from https://github.com/babel/babel/blob/72c091b63a1f443fdae34e89c821eb0e35eef3ed/packages/babel-plugin-transform-runtime/src/index.js#L41-L45

edit: the current code makes this plugin unusable for libs

> Another purpose of this transformer is to create a sandboxed environment for your code. If you use babel-polyfill and the built-ins it provides such as Promise, Set and Map, those will pollute the global scope. While this might be ok for an app or a command line tool, it becomes a problem if your code is a library which you intend to publish for others to use or if you can’t exactly control the environment in which your code will run.

https://babeljs.io/docs/plugins/transform-runtime/

**Comment by chpio** [comment]
is this package abandoned? do i need to fork it?

**Comment by treywood** [comment]
This package was my first foray into managing an open source project, so I apologize if it's a bit sloppy. I haven't been working actively on it for the past few months, and in fact by now it's superseded by one of Babel's own plugins: http://babeljs.io/docs/plugins/transform-async-to-module-method.

That plugin is configurable enough to cover this sort of thing.

**Comment by chpio** [comment]
ohh, ok

> That plugin is configurable enough to cover this sort of thing.

hmm, but it's building generators for simple async functions too that's kinda uncool.
